version: "3"
networks:
    app-tier:
        driver: bridge
services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        networks:
            - app-tier
        ports:
            - 9002:9000
        volumes:
            - .:/var/www/html
    nginx:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        networks:
            - app-tier
        ports:
            - 8080:80
        volumes:
            - ./public:/var/ww/html/public

