version: "3"
networks:
    app-tier:
        driver: bridge
services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        networks:
            - app-tier
        ports:
            - 9002:9000
        volumes:
            - .:/var/www/html
        links:
            - mariadb:mariadb
    nginx:
        depends_on:
            - app
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        networks:
            - app-tier
        ports:
            - 8080:80
        volumes:
            - ./public:/var/www/html/public
    mariadb:
        image: mariadb:10.1.21
        ports:
            - "13306:3306"
        networks:
            - app-tier
        environment:
            - MYSQL_DATABASE=devbox
            - MYSQL_ROOT_PASSWORD=password
